[2024-08-23T13:23:32.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-23T13:23:32.384627+00:00 [queued]>
[2024-08-23T13:23:32.924+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-23T13:23:32.384627+00:00 [queued]>
[2024-08-23T13:23:32.924+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 61
[2024-08-23T13:23:32.935+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): new_json_file_sensor> on 2024-08-23 13:23:32.384627+00:00
[2024-08-23T13:23:32.942+0000] {standard_task_runner.py:60} INFO - Started process 2165 to run task
[2024-08-23T13:23:32.946+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'json_FT_processing_pipeline_03', 'new_json_file_sensor', 'manual__2024-08-23T13:23:32.384627+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/FranceTravail_pipeline_dag03.py', '--cfg-path', '/tmp/tmpwtdfhi13']
[2024-08-23T13:23:32.948+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask new_json_file_sensor
[2024-08-23T13:23:32.966+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-23T13:23:32.997+0000] {task_command.py:423} INFO - Running <TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-23T13:23:32.384627+00:00 [running]> on host 9e648299db30
[2024-08-23T13:23:33.073+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='json_FT_processing_pipeline_03' AIRFLOW_CTX_TASK_ID='new_json_file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-08-23T13:23:32.384627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-23T13:23:32.384627+00:00'
[2024-08-23T13:23:33.084+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:23:33.084+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:23:43.102+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:23:43.102+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:23:53.119+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:23:53.119+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:03.135+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:03.137+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:13.154+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:13.154+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:23.171+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:23.172+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:33.186+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:33.186+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:43.202+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:43.203+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:24:53.218+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:24:53.218+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:25:03.237+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T13:25:03.237+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T13:25:08.910+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-08-23T13:25:08.912+0000] {process_utils.py:131} INFO - Sending 15 to group 2165. PIDs of all processes in the group: [2165]
[2024-08-23T13:25:08.912+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2165
[2024-08-23T13:25:08.913+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-23T13:25:08.920+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-08-23T13:25:08.927+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=json_FT_processing_pipeline_03, task_id=new_json_file_sensor, execution_date=20240823T132332, start_date=20240823T132332, end_date=20240823T132508
[2024-08-23T13:25:08.940+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task new_json_file_sensor ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(json_FT_processing_pipeline_03, new_json_file_sensor, manual__2024-08-23T13:23:32.384627+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'new_json_file_sensor', 'dag_id': 'json_FT_processing_pipeline_03', 'run_id': 'manual__2024-08-23T13:23:32.384627+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 8, 23, 13, 23, 32, 916806, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 8, 23, 13, 25, 8, 926991, tzinfo=Timezone('UTC')), 'duration': 96}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2165)
[2024-08-23T13:25:08.965+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2165, status='terminated', exitcode=1, started='13:23:32') (2165) terminated with exit code 1
