[2024-08-22T15:15:09.034+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-22T15:15:08.588963+00:00 [queued]>
[2024-08-22T15:15:09.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-22T15:15:08.588963+00:00 [queued]>
[2024-08-22T15:15:09.043+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 61
[2024-08-22T15:15:09.056+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): new_json_file_sensor> on 2024-08-22 15:15:08.588963+00:00
[2024-08-22T15:15:09.061+0000] {standard_task_runner.py:60} INFO - Started process 15652 to run task
[2024-08-22T15:15:09.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'json_FT_processing_pipeline_03', 'new_json_file_sensor', 'manual__2024-08-22T15:15:08.588963+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/FranceTravail_pipeline_dag03.py', '--cfg-path', '/tmp/tmpy0s2wvmg']
[2024-08-22T15:15:09.066+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask new_json_file_sensor
[2024-08-22T15:15:09.080+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-22T15:15:09.117+0000] {task_command.py:423} INFO - Running <TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor manual__2024-08-22T15:15:08.588963+00:00 [running]> on host f25666c00f72
[2024-08-22T15:15:09.192+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='json_FT_processing_pipeline_03' AIRFLOW_CTX_TASK_ID='new_json_file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T15:15:08.588963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T15:15:08.588963+00:00'
[2024-08-22T15:15:09.202+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:09.202+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:15:19.218+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:19.218+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:15:29.233+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:29.234+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:15:39.247+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:39.248+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:15:49.262+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:49.263+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:15:59.280+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:15:59.281+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:09.298+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:09.299+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:19.310+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:19.310+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:29.329+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:29.329+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:39.351+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:39.351+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:49.368+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:49.369+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:16:59.388+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:16:59.389+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:17:09.406+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-22T15:17:09.407+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-22T15:17:15.412+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-08-22T15:17:15.414+0000] {process_utils.py:131} INFO - Sending 15 to group 15652. PIDs of all processes in the group: [15652]
[2024-08-22T15:17:15.414+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 15652
[2024-08-22T15:17:15.414+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-22T15:17:15.425+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-08-22T15:17:15.430+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=json_FT_processing_pipeline_03, task_id=new_json_file_sensor, execution_date=20240822T151508, start_date=20240822T151509, end_date=20240822T151715
[2024-08-22T15:17:15.442+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task new_json_file_sensor ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(json_FT_processing_pipeline_03, new_json_file_sensor, manual__2024-08-22T15:15:08.588963+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'new_json_file_sensor', 'dag_id': 'json_FT_processing_pipeline_03', 'run_id': 'manual__2024-08-22T15:15:08.588963+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 8, 22, 15, 15, 9, 34895, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 8, 22, 15, 17, 15, 430072, tzinfo=Timezone('UTC')), 'duration': 126}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 15652)
[2024-08-22T15:17:15.468+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=15652, status='terminated', exitcode=1, started='15:15:08') (15652) terminated with exit code 1
