[2024-08-23T21:28:29.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor scheduled__2024-08-22T08:00:00+00:00 [queued]>
[2024-08-23T21:28:29.288+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor scheduled__2024-08-22T08:00:00+00:00 [queued]>
[2024-08-23T21:28:29.288+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 62
[2024-08-23T21:28:29.298+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): new_json_file_sensor> on 2024-08-22 08:00:00+00:00
[2024-08-23T21:28:29.305+0000] {standard_task_runner.py:60} INFO - Started process 17446 to run task
[2024-08-23T21:28:29.308+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'json_FT_processing_pipeline_03', 'new_json_file_sensor', 'scheduled__2024-08-22T08:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/FranceTravail_pipeline_dag03.py', '--cfg-path', '/tmp/tmp3wallau8']
[2024-08-23T21:28:29.309+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask new_json_file_sensor
[2024-08-23T21:28:29.324+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-23T21:28:29.364+0000] {task_command.py:423} INFO - Running <TaskInstance: json_FT_processing_pipeline_03.new_json_file_sensor scheduled__2024-08-22T08:00:00+00:00 [running]> on host 9e648299db30
[2024-08-23T21:28:29.435+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='json_FT_processing_pipeline_03' AIRFLOW_CTX_TASK_ID='new_json_file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-22T08:00:00+00:00'
[2024-08-23T21:28:29.445+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T21:28:29.446+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T21:28:39.462+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T21:28:39.462+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T21:28:49.481+0000] {base.py:83} INFO - Using connection ID 'fs_jobmarket' for task execution.
[2024-08-23T21:28:49.481+0000] {filesystem.py:66} INFO - Poking for file /opt/***/ETL/Json_temp
[2024-08-23T21:28:54.578+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-08-23T21:28:54.579+0000] {process_utils.py:131} INFO - Sending 15 to group 17446. PIDs of all processes in the group: [17446]
[2024-08-23T21:28:54.579+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 17446
[2024-08-23T21:28:54.580+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-23T21:28:54.606+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=17446, status='terminated', exitcode=0, started='21:28:28') (17446) terminated with exit code 0
